name: Semgrep fast scan SAST

on:
  pull_request:
    branches: [ "main" ]

jobs:
  semgrep:
    name: Analisi del codice
    runs-on: ubuntu-latest
    
    steps:
      - name: Clona la repository
        uses: actions/checkout@v4
      - run: semgrep scan --congif auto --error